version: "3.8"

services:
  db:
    image: mariadb:10.11
    container_name: employee-db
    environment:
      MYSQL_ROOT_PASSWORD: santoor711
      MYSQL_DATABASE: emp
      MYSQL_USER: employee
      MYSQL_PASSWORD: santoor711
    ports:
      - "3306:3306"
    volumes:
      - employeedb_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    image: santoshkumar711/employee-app:v1
    container_name: employee-app
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/emp
      SPRING_DATASOURCE_USERNAME: employee
      SPRING_DATASOURCE_PASSWORD: santoor711
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
    restart: always

volumes:
  employeedb_data:
