version: "3.8"

services:
  db:
    image: mariadb:10.11
    container_name: employee-db
    environment:
      MYSQL_ROOT_PASSWORD: santoor711
      MYSQL_DATABASE: employee
      MYSQL_USER: employee
      MYSQL_PASSWORD: santoor711
    ports:
      - "3306:3306"
    volumes:
      - employeedb_data:/var/lib/mysql
    restart: unless-stopped

  app:
    image: santoshkumar711/employee-app:v1
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/employee
      SPRING_DATASOURCE_USERNAME: employee
      SPRING_DATASOURCE_PASSWORD: santoor711
    restart: always

volumes:
  employeedb_data:
